# Generated by Django 6.0.4 on 2026-04-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_prestador_endereco_prestador_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='dias_funcionamento',
        ),
        migrations.AddField(
            model_name='prestador',
            name='dia_fim',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='dia_inicio',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True),
        ),
    ]
