# Generated by Django 6.0.4 on 2026-05-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_prestador_dias_funcionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='profissional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
