# Generated by Django 6.0.4 on 2026-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servico_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueio',
            name='profissional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
